apiVersion: v1
kind: Service
metadata:
  name: app-tier
  labels:
    app: microservices

spec:
  ports:
  - port: 8080
  selector:
    tier: app

---

apiVersion: v1
kind: Pod
metadata:
  name: app-tier
  labels:
    app: microservices
    tier: app

spec:
  containers:
  - name: server
    image: lrakai/microservices:server-v1
    ports:
      - containerPort: 8080
# Service discovery mechanisms ..... Environment variables
    env:
      - name: REDIS_URL
        value: redis://$(DATA_TIER_SERVICE_HOST):(DATA_TIER_SERVICE_PORT_REDIS)




# HOW WE CAN DEFINE THE ENVAROMENT?
    # The general formula to define the envaroment is  "$(NodeIP:NodePort)""
# WHAT IS THE VALUE IF NODEIP AND NODEPORT?

# NODEIP VALUE = SERVICENAME_SERVICE_HOST
# NODEPORT VALUE = SERVICENAME_SERVICE_HOST_PORTNAME(ITS OPTIONAL)




# Environment variable service discovery
# Naming pattern:
# IP address: <all_caps_service_name>_SERVICE_HOST
# Port: <all_caps_service_name>_SERVICE_PORT
# Named Port: <all_caps_service_name>_SERVICE_PORT_<all_caps_port_name>
  